In [68]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# import tensorflow as tf
# from tensorflow import keras

In [69]:
data=pd.read_csv("train.csv")

In [ ]:
data.head()

In [70]:
data=np.array(data)
m,n=data.shape
np.random.shuffle(data)

data_dev=data[0:1000].T
Y_dev=(data_dev[0])
X_dev=(data_dev[1:n])
X_dev=X_dev/255

data_train=data[1000:m].T
Y_train=(data_train[0])
X_train=(data_train[1:n])
X_train=X_train/255
_,m_train=X_train.shape




In [ ]:
print(Y_train.shape)
print(X_train[:].shape)

In [71]:
def init_params():
    W1=np.random.rand(10,784)-0.5
    b1=np.random.rand(10,1)-0.5
    W2=np.random.rand(10,10)-0.5
    b2=np.random.rand(10,1)-0.5

    return W1,b1,W2,b2

def ReLU(Z):
    return np.maximum(0,Z)

def softmax(Z):
    A=np.exp(Z)/sum(np.exp(Z))
    return A

def forward_prop(W1,b1,W2,b2,X):
    Z1=W1.dot(X)+b1
    A1=ReLU(Z1)
    Z2=W2.dot(A1)+b2
    A2=ReLU(Z2)

    return Z1,A1,Z2,A2

def one_hot(Y):
    one_hot_Y=np.zeros((Y.size,Y.max()+1))
    one_hot_Y[np.arange(Y.size),Y]=1
    one_hot_Y=one_hot_Y.T

    return one_hot_Y

def deriv_ReLU(Z):
    return Z>0

def back_prop(Z1,A1,Z2,A2,W1,W2,X,Y):
    m=Y.size
    one_hot_Y=one_hot(Y)
    dZ2=A2-one_hot_Y
    dW2=1/m*dZ2.dot(A1.T)
    db2=1/m*np.sum(dZ2)
    dZ1=W2.T.dot(dZ2)*deriv_ReLU(Z1)
    dW1=1/m*dZ1.dot(X.T)
    db1=1/m*np.sum(dZ1)


    return dW1,db1,dW2,db2

def update_params(W1,b1,W2,b2,dW1,db1,dW2,db2,eta):
    W1=W1-eta*dW1
    b1=b1-eta*db1
    W2=W2-eta*dW2
    b2=b2-eta*db2

    return W1,b1,W2,b2

In [72]:
def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions,Y):
    print(predictions,Y)
    return np.mean(predictions==Y)

def gradient_descent(X, Y, alpha, iterations,lst):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
        # if i==iterations-1:
        #     predictions = get_predictions(A2)
        #     print(alpha, get_accuracy(predictions, Y))
        #     lst.append((alpha, get_accuracy(predictions, Y)))
    return W1, b1, W2, b2

In [ ]:
eta=0.2
lst=[]
while eta<0.3:
    print("Running with eta = ",eta)
    W1,b1,W2,b2=gradient_descent(X_train,Y_train,eta,3000,lst)
    eta+=0.01
print("Your results across various hyperparameters:",lst)

In [84]:
#0.2 and 0.26 is the best learning rate
lst=[]
W1,b1,W2,b2=gradient_descent(X_train,Y_train,0.26,3000,lst)

Iteration:  0
[1 5 5 ... 3 5 5] [8 5 0 ... 8 2 9]
0.08553658536585367
Iteration:  10
[9 9 9 ... 9 2 9] [8 5 0 ... 8 2 9]
0.16363414634146342
Iteration:  20
[9 9 9 ... 9 2 9] [8 5 0 ... 8 2 9]
0.17424390243902438
Iteration:  30
[9 9 9 ... 9 2 9] [8 5 0 ... 8 2 9]
0.1881219512195122
Iteration:  40
[9 9 9 ... 9 2 2] [8 5 0 ... 8 2 9]
0.2
Iteration:  50
[9 9 9 ... 2 2 4] [8 5 0 ... 8 2 9]
0.21417073170731707
Iteration:  60
[9 9 0 ... 2 2 3] [8 5 0 ... 8 2 9]
0.2668048780487805
Iteration:  70
[2 2 0 ... 2 2 3] [8 5 0 ... 8 2 9]
0.32190243902439025
Iteration:  80
[3 3 0 ... 7 2 3] [8 5 0 ... 8 2 9]
0.3510243902439024
Iteration:  90
[3 3 0 ... 8 2 3] [8 5 0 ... 8 2 9]
0.3706341463414634
Iteration:  100
[3 3 0 ... 8 2 3] [8 5 0 ... 8 2 9]
0.380609756097561
Iteration:  110
[3 3 0 ... 8 9 3] [8 5 0 ... 8 2 9]
0.3907317073170732
Iteration:  120
[3 3 0 ... 8 9 3] [8 5 0 ... 8 2 9]
0.40290243902439027
Iteration:  130
[3 3 0 ... 8 9 3] [8 5 0 ... 8 2 9]
0.4113170731707317
Iteration:  140
[3 3 0 ... 

In [85]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()

In [86]:
dev_predictions = make_predictions(X_dev, W1, b1, W2, b2)
get_accuracy(dev_predictions, Y_dev)

[2 9 7 3 9 3 3 1 7 9 9 3 3 6 9 7 7 6 1 2 4 9 3 4 3 4 6 5 6 6 8 0 7 8 9 1 3
 4 6 2 3 7 5 2 4 0 8 7 3 1 9 1 4 7 4 6 2 0 1 1 0 1 6 6 1 2 1 4 4 4 3 7 2 0
 2 8 9 9 0 1 4 4 1 6 2 7 9 8 9 8 2 3 8 3 7 1 8 1 8 4 8 1 9 7 4 7 3 2 3 1 5
 9 4 8 0 8 9 7 1 4 6 6 3 9 2 6 9 5 9 6 6 8 4 1 4 8 1 6 5 0 8 9 1 4 6 9 9 6
 9 7 8 3 2 0 1 4 9 0 1 7 1 1 9 1 8 1 0 4 4 5 3 7 6 1 2 3 8 8 0 7 3 6 6 5 8
 6 3 8 7 4 5 2 0 4 6 1 7 9 8 7 8 5 8 0 2 7 4 7 7 9 2 8 0 3 1 2 9 3 0 8 2 8
 7 8 7 0 8 2 6 3 6 3 0 9 0 9 0 6 0 8 4 6 9 5 6 1 5 3 5 3 0 8 4 6 7 1 9 7 9
 3 7 0 1 7 5 2 4 6 8 8 9 6 0 5 8 8 8 1 8 7 0 7 9 5 2 8 4 1 1 2 1 4 1 8 1 5
 4 3 4 3 3 9 1 4 1 4 7 8 4 7 3 8 8 1 7 3 4 0 1 3 8 9 5 1 4 7 7 4 7 1 3 3 6
 7 4 6 5 7 7 0 4 0 3 7 0 8 3 4 2 3 8 1 7 2 6 4 6 7 1 9 7 6 2 6 1 0 4 6 4 7
 7 6 1 8 7 9 0 8 9 5 8 6 0 3 3 5 6 8 1 6 4 0 0 4 6 9 1 3 0 0 4 6 7 9 1 7 6
 0 6 6 2 2 7 7 9 8 9 9 0 6 7 1 3 1 6 6 8 8 0 3 8 5 8 9 7 0 6 9 8 7 7 0 0 3
 1 6 5 4 8 1 3 1 1 4 9 0 6 6 2 1 5 0 4 3 6 1 1 3 6 8 6 8 8 5 4 7 0 3 4 4 6
 9 3 8 1 2 0 6 7 8 8 9 7 

0.82